spring.application.name=Smart Expense Splitter
# application.properties
spring.datasource.url=jdbc:postgresql://localhost:5432/smart_expense_splitter
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
 # Use 'update' for development, consider migration tools for production
spring.mvc.servlet.path=/api
logging.level.org.springframework.web=debug
logging.level.org.hibernate.SQL=DEBUG